name: EUM Server Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_call:

env:
  NVD_API_TOKEN: ${{ secrets.NVD_API_KEY }} # Token to access NVD API for dependency-check

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-slim
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: test
        run: ./gradlew test

  dependency-scan:
    needs: test
    name: Dependency Scan
    runs-on: ubuntu-latest
    container: openjdk:17-jdk-slim
    steps:
      - uses: actions/checkout@v3
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: build
        run: ./gradlew assemble
      - name: dependency check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'inspectit-ocelot-eum-server'
          path: '.'
          format: 'HTML'
          out: 'reports'
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: DependencyCheck-Report
          path: ${{github.workspace}}/reports
